// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using rutinadeldiaservidor.Data;

#nullable disable

namespace rutinadeldiaservidor.Migrations
{
    [DbContext(typeof(RutinaContext))]
    [Migration("20250926171822_updateRecordatorio")]
    partial class updateRecordatorio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("rutinadeldiaservidor.Models.Adulto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("Pin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Adultos");
                });

            modelBuilder.Entity("rutinadeldiaservidor.Models.Infante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InfanteNivelId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InfanteNivelId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Infantes");
                });

            modelBuilder.Entity("rutinadeldiaservidor.Models.InfanteNivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InfanteNiveles");
                });

            modelBuilder.Entity("rutinadeldiaservidor.Models.Paso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Audio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("RutinaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RutinaId");

                    b.ToTable("Pasos");
                });

            modelBuilder.Entity("rutinadeldiaservidor.Models.Recordatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<int>("RutinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Sonido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RutinaId")
                        .IsUnique();

                    b.ToTable("Recordatorios");
                });

            modelBuilder.Entity("rutinadeldiaservidor.Models.Rutina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("rutinadeldiaservidor.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("rutinadeldiaservidor.Models.Adulto", b =>
                {
                    b.HasOne("rutinadeldiaservidor.Models.Usuario", "Usuario")
                        .WithOne("Adulto")
                        .HasForeignKey("rutinadeldiaservidor.Models.Adulto", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("rutinadeldiaservidor.Models.Infante", b =>
                {
                    b.HasOne("rutinadeldiaservidor.Models.InfanteNivel", "InfanteNivel")
                        .WithMany()
                        .HasForeignKey("InfanteNivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rutinadeldiaservidor.Models.Usuario", "Usuario")
                        .WithMany("Infantes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InfanteNivel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("rutinadeldiaservidor.Models.Paso", b =>
                {
                    b.HasOne("rutinadeldiaservidor.Models.Rutina", "Rutina")
                        .WithMany("Pasos")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("rutinadeldiaservidor.Models.Recordatorio", b =>
                {
                    b.HasOne("rutinadeldiaservidor.Models.Rutina", "Rutina")
                        .WithOne("Recordatorio")
                        .HasForeignKey("rutinadeldiaservidor.Models.Recordatorio", "RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("rutinadeldiaservidor.Models.Rutina", b =>
                {
                    b.Navigation("Pasos");

                    b.Navigation("Recordatorio");
                });

            modelBuilder.Entity("rutinadeldiaservidor.Models.Usuario", b =>
                {
                    b.Navigation("Adulto")
                        .IsRequired();

                    b.Navigation("Infantes");
                });
#pragma warning restore 612, 618
        }
    }
}
